# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c') + Glob('*.cpp')
CPPPATH = [cwd]

group = DefineGroup('testsuite', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
